// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvZdQLnr1K6HfRV5xihpm7A-x64VQdE-s',
    appId: '1:825506108526:web:df0674edf2f8815c73c27f',
    messagingSenderId: '825506108526',
    projectId: 'sspkm-561e4',
    authDomain: 'sspkm-561e4.firebaseapp.com',
    storageBucket: 'sspkm-561e4.appspot.com',
    measurementId: 'G-NB0YWEDMV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ecP5AJfwTToj0EyqJz3ppsh2MzS4GQQ',
    appId: '1:825506108526:android:b5820697ca5b113773c27f',
    messagingSenderId: '825506108526',
    projectId: 'sspkm-561e4',
    storageBucket: 'sspkm-561e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQR8w4aqrA2O0vdq4B2LCkqOoap8PG_XU',
    appId: '1:825506108526:ios:f060d99a9782384773c27f',
    messagingSenderId: '825506108526',
    projectId: 'sspkm-561e4',
    storageBucket: 'sspkm-561e4.appspot.com',
    androidClientId: '825506108526-rps3bpjsg09k55ejdldsdqp549vmgqrc.apps.googleusercontent.com',
    iosClientId: '825506108526-ssgpol46b7c1imigk7n6pm6qi8dlca29.apps.googleusercontent.com',
    iosBundleId: 'com.example.sspkm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQR8w4aqrA2O0vdq4B2LCkqOoap8PG_XU',
    appId: '1:825506108526:ios:f060d99a9782384773c27f',
    messagingSenderId: '825506108526',
    projectId: 'sspkm-561e4',
    storageBucket: 'sspkm-561e4.appspot.com',
    androidClientId: '825506108526-rps3bpjsg09k55ejdldsdqp549vmgqrc.apps.googleusercontent.com',
    iosClientId: '825506108526-ssgpol46b7c1imigk7n6pm6qi8dlca29.apps.googleusercontent.com',
    iosBundleId: 'com.example.sspkm',
  );
}
